### ISSUE TITLE
Server and Client add name doesn't work

### ISSUE THREAD

**Issue by SabaBegum2** [SabaBegum2/SimpleFullStackApp#8]
Server and Client add name doesn't work maybe because the same database is being used for backend and frontend?

**Comment by violetyousif** [comment]
Possibly but there's more editing we need to do before we can see the changes. It's little things we just haven't gotten to yet. I just changed a few like the db "names" needed to be changed to "Users" instead. I'm about to edit the html page as well because the headers aren't compatible with our table either.

**Comment by SabaBegum2** [comment]
Sounds good!

**Comment by violetyousif** [comment]
Appears to be working after minor renaming changes were made!
